name: Continuous Delivery
run-name: Upload CLI release to S3
on:
  workflow_run:
    workflows:
      - Continuous Integration
    branches:
      - main
    types:
      - completed

jobs:
  upload:
    name: Upload artifacts
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 LDFLAGS="-w -s" nix develop --command mage
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::152560469324:role/captain-cli-cd
          role-duration-seconds: 900
      - run: |
          version=$(nix develop --command go run ./cmd/captain --version)
          artifact_name=$(echo "captain-${{ matrix.os }}-${{ matrix.arch }}-$version" | tr '[:upper:]' '[:lower:]')
          aws s3 mv ./captain "s3://terraform-20221109133415397600000001/$artifact_name"
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
        if: ${{ matrix.os != 'windows' }}
      - run: |
          version=$(nix develop --command go run ./cmd/captain --version)
          artifact_name=$(echo "captain-${{ matrix.os }}-${{ matrix.arch }}-$version" | tr '[:upper:]' '[:lower:]')
          aws s3 mv ./captain.exe "s3://terraform-20221109133415397600000001/$artifact_name"
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
        if: ${{ matrix.os == 'windows' }}

  deliver-binaries:
    name: Deliver binaries
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      id-token: write
    needs: upload
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::152560469324:role/captain-cli-cd
          role-duration-seconds: 900
      - id: list-bucket
        run: |
          objects=$(aws s3api list-objects --bucket terraform-20221109133415397600000001 --no-paginate --query 'Contents[].Key' --output=json | jq -r '.[]')

          echo "objects<<EOF" >> "$GITHUB_OUTPUT"
          echo "$objects" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - id: find-versions
        run: |
          versions=$(echo "${{ steps.list-bucket.outputs.objects }}" | grep "[-]v" | sed 's/.*-v/v/' | sed '/-/!{s/$/_/}' | sort -ruV | sed 's/_$//' | grep -v "^v1$")
          allVersions=$(printf "%s\n" $versions | jq --raw-input | jq --slurp)
          latestV1=$(printf "%s\n" $versions | grep -v "-" | grep "v1" | head -n 1)

          echo "allVersions<<EOF" >> "$GITHUB_OUTPUT"
          echo "$allVersions" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          echo "latestV1=$latestV1" >> "$GITHUB_OUTPUT"
      - id: release-versions
        run: |
          jq -n \
            --argjson versions '${{ steps.find-versions.outputs.allVersions }}' \
            --arg latestV1 '${{ steps.find-versions.outputs.latestV1 }}' \
            '{captain: {v1: $latestV1, versions: $versions}}' > versions.json

          latestV1Binaries=$(echo "${{ steps.list-bucket.outputs.objects }}" | grep -E '^captain-[^-]+-[^-]+-${{ steps.find-versions.outputs.latestV1 }}$')

          echo "Uploading versions.json"
          aws s3 mv ./versions.json "s3://terraform-20221109133415397600000001/versions.json"
          paths="\"/versions.json\""

          for binary in $latestV1Binaries
          do
            aliasedBinary=$(echo "$binary" | sed "s/${{ steps.find-versions.outputs.latestV1 }}/v1/g")
            echo "Uploading $binary to $aliasedBinary"
            aws s3 cp "s3://terraform-20221109133415397600000001/$binary" "s3://terraform-20221109133415397600000001/$aliasedBinary"
            paths="$paths \"/$aliasedBinary\""
          done

          echo "updatedPaths=$paths" >> "$GITHUB_OUTPUT"
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths ${{ steps.release-versions.outputs.updatedPaths }}
