name: Continuous Integration
on:
  push:
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - run: CGO_ENABLED=0 LDFLAGS="-w -s" nix develop --command mage
      - run: |
          REPORT=true ./captain run \
            --suite-id="captain-cli-ginkgo" \
            --github-job-name="Build & Test" \
            --github-job-matrix='${{ toJSON(matrix) }}' \
            --test-results=report.xml \
            --fail-on-upload-error \
            -- nix develop --command mage test
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
      - run: ./test/functional.sh
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
      - run: ./test/functional-abq.sh
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - run: nix develop --command mage lint
      - run: nix fmt -- --check flake.nix
