name: Merge Requirements
on:
  pull_request:
jobs:
  check-version:
    name: Ensure version bump
    runs-on: ubuntu-latest
    if: ${{ github.head_ref != 'main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - run: |
          newVersion=$(cat version.go | grep "const Version" | awk '{print $4}' | sed 's/"//g')
          git fetch && git checkout origin/main
          oldVersion=$(cat version.go | grep "const Version" | awk '{print $4}' | sed 's/"//g')
          if [[ "$newVersion" == "$oldVersion" ]]; then
            echo "Version number was not changed"
            exit 1
          fi
          latestVersion=$(echo "$newVersion $oldVersion" | sed 's/\ /\n/' | sort -rV | head -n 1)
          if [[ "$latestVersion" != "$newVersion" ]]; then
            echo "Version number was not increased"
            exit 1
          fi
